### ISSUE TITLE
not support ssr

### ISSUE THREAD

**Issue by qaz3954179** [loadingwyn/react-imageslides#14]
not support ssr?
framework: egg-react-ssr
Error:
Page Controller renderToStream Error ReferenceError: window is not defined
[0] [0]     at Object.<anonymous> (/code/node_modules/react-imageslides/dist/webpack:/react-imageslides/webpack/universalModuleDefinition:10:4)
[0] [0]     at Module._compile (internal/modules/cjs/loader.js:701:30)
[0] [0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
[0] [0]     at Module.load (internal/modules/cjs/loader.js:600:32)
[0] [0]     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
[0] [0]     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[0] [0]     at Module.require (internal/modules/cjs/loader.js:637:17)
[0] [0]     at require (internal/modules/cjs/helpers.js:22:18)
[0] [0]     at eval (webpack-internal:///react-imageslides:1:18)

**Comment by loadingwyn** [comment]
I'm working on it

**Comment by qaz3954179** [comment]
use egg-react-ssr?

**Comment by qaz3954179** [comment]
[0] [0] 2020-09-27 22:17:14,505 ERROR 60237 [-/127.0.0.1/-/4ms GET /] Page Controller renderToStream Error ReferenceError: window is not defined
[0] [0]     at Object.<anonymous> (/gitee/yktest/node_modules/react-imageslides/dist/bundle.js:1:399)
[0] [0]     at Module._compile (internal/modules/cjs/loader.js:701:30)
[0] [0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
[0] [0]     at Module.load (internal/modules/cjs/loader.js:600:32)
[0] [0]     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
[0] [0]     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[0] [0]     at Module.require (internal/modules/cjs/loader.js:637:17)
[0] [0]     at require (internal/modules/cjs/helpers.js:22:18)
[0] [0]     at eval (webpack-internal:///react-imageslides:1:18)
[0] [0]     at Object.react-imageslides (/gitee/yktest/dist/Page.server.js:233:1)

**Comment by loadingwyn** [comment]
> use egg-react-ssr?

I mean I'm working on fixing it

**Comment by loadingwyn** [comment]
this issue is caused by [css3transform](https://github.com/Tencent/omi/blob/master/packages/omi-transform/css3transform/dist/css3transform.js). There is no way to walk around it on my side. So just don't ssr it. 
BTW, this component is more like a functional component. Usually, it should not be a part of your content.

**Comment by qaz3954179** [comment]
get

**Comment by loadingwyn** [comment]
If you really want ssr, you can try v3.0. I have removed css3transform
